version: 2
jobs:

  test:
    working_directory: /go/src/github.com/konojunya/HEW2018
    docker:
      - image: makki0205/deploy

    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: component build
          command: npm run build
      - save_cache:
          key: build-{{ epoch }}
          paths:
            - .
  
  gotest:
    working_directory: /go/src/github.com/konojunya/HEW2018
    docker:
      - image: makki0205/deploy

    steps:
      - checkout
      - run:
          name: go test
          command: go test -v ./service/...
      - run:
          name: go build
          command: make go/build

  deploy:
    working_directory: /go/src/github.com/konojunya/HEW2018
    docker:
      - image: makki0205/deploy

    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
      - restore_cache:
          keys:
            - build
      - run:
          name: migration
          command: make migrate
      - run:
          name: docker login
          command: make docker/login
      - run:
          name: docker build
          command: make docker/build
      - run:
          name: docker push
          command: make docker/push

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - gotest
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
